import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "@/app/ui/styles/globals.css";
import { SessionProvider } from "next-auth/react";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}